use List replace Queue, use batch api to send 1~n tracks
poumason/GoogleAnalyticsClientDotNet pull request #13
Opened 2017-01-06 09:18 UTC by poumason

use List replace Queue, use batch api to send 1~n tracks 
typo PING_PONG, HeartBeat, open EnabledHeartBeat property

2017-01-06 10:16 UTC, renewal-wu requested changes

2017-01-06 10:16 UTC, renewal-wu commented on Library/GoogleAnalyticsClientDotNet.Shared/BaseAnalyticsService.cs
> +        private async Task<IEnumerable<string>> ImportEvents()
命名應該調整一下

2017-01-09 01:58 UTC, FatJohn reviewed
幾個調整一下

2017-01-09 01:58 UTC, FatJohn commented on Library/GoogleAnalyticsClientDotNet.Shared/BaseAnalyticsService.cs
> +                    await Task.Delay(CommonDefine.POSITION_TIMER_INTERVAL);
POSITION_TIMER_INTERVAL 命名要換一下

2017-01-09 01:58 UTC, FatJohn commented on Library/GoogleAnalyticsClientDotNet.Shared/BaseAnalyticsService.cs
> +                var task = HttpService.PostAsync(CommonDefine.GOOGLE_ANALYTICS_BATCH_URL, batchTracks);
雖然沒有 await 不過還是加一下 try catch
不過這邊沒有 await 的話，前後一次發送就會連續送是預期的？

2017-01-09 01:58 UTC, FatJohn commented on Library/GoogleAnalyticsClientDotNet.Shared/ServiceModel/Service/HttpService.cs
> +                if (HttpInstance == null)
Dispose 裡面的 GC.SuppressFinalize(this); 可以拿掉，這行是告訴 GC 不要執行 Finalizer，但這邊不需要

2017-01-09 02:33 UTC, FatJohn approved these changes

2017-01-09 02:37 UTC, merged